# todo: auto remove, name, etc..
services:
  bank-api:
    build:
      context: ./bank-api
    ports:
      - "4001:4000"
    networks:
      - dev

  bank-client:
    build:
      context: ./bank-client
    ports:
      - "3001:3000"
    networks:
      - dev
networks:
  dev:
    driver: bridge