name: Code coverage tests
on:
   push:
     branches: [ "main", "dev" ]
   pull_request:
     branches: [ "main", "dev" ]

jobs:
   test-job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Use Node 18.16.0
       uses: actions/setup-node@v3
       with:
         node-version: '18.16.0'

     - name: Install dependencies
       run: npm i

     - name: Run code coverage test
       run: npm run test

     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v3
